---
- name: MySQL client | Debian | install Percona repo key
  apt_key: keyserver="{{ percona_key_serv }}" id="{{ percona_apt_key }}"

- name: MySQL client | Debian | install Percona repo
  apt_repository: repo="{{ percona_apt_repo }}" state=present

- name: MySQL client | Debian | install packages
  apt: name="{{ item }}" update_cache=yes state=present 
  with_items:
    - percona-server-client-5.6
    - percona-toolkit
    - percona-xtrabackup
